apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: helloworld-controllers
  labels:
    app: helloworld
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: k8s-pod-demo
        image: mzain/k8s-java-app
        ports:
        - name: java-port
          containerPort: 8080
  selector:
    matchLabels:
      app: helloworld
