apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  selector:
    matchLabels:
      app: devops-app
  replicas: 4
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      containers:
      - name: k8s-demo
        image: nginx
        ports:
        - name: nginx-port
          containerPort: 80
